-- LAST GENRATED IDENTITY COLUMN VALUE
CREATE TABLE Test1(
   ID INT IDENTITY(1,1),
   Value nvarchar(20)
);

CREATE TABLE Test2(
   ID INT IDENTITY(1,1),
   Value nvarchar(20)
);

INSERT INTO Test1
VALUES ('X');

SELECT 4 FROM Test1;

SELECT SCOPE_IDENTITY();
SELECT @@IDENTITY;
SELECT IDENT_CURRENT('Test2')

CREATE TRIGGER trForInsert 
ON Test1 for INSERT
AS
BEGIN
   INSERT INTO Test2
   VALUES ('YYYY')
END;

SELECT * FROM Test1;
SELECT * FROM Test2;