
-- CHAP 84

USE SQL_STORE;

START TRANSACTION;

INSERT INTO ORDERS (customer_id,order_date,status)
VALUES (1,'2019/01/01',1);

INSERT INTO order_items
VALUES (LAST_INSERT_ID(),1,1,1); 

ROLLBACK;

COMMIT;

-- CHAP 85

USE SQL_STORE;

START TRANSACTION;
UPDATE customers
SET POINTS = POINTS + 10
WHERE CUSTOMER_ID = 1;
COMMIT;

-- CHAP 87

SHOW VARIABLES LIKE 'TRANSACTION_ISOLATION';
SET SESSION TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SET GLOBAL TRANSACTION ISOLATION LEVEL SERIALIZABLE;

-- CHAP 88
USE SQL_STORE;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SELECT POINTS
FROM CUSTOMERS
WHERE CUSTOMER_ID = 1;

-- CHAP 89

USE SQL_STORE;
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
START TRANSACTION;
SELECT POINTS FROM CUSTOMERS WHERE CUSTOMER_ID = 1;
SELECT POINTS FROM CUSTOMERS WHERE CUSTOMER_ID = 1;
COMMIT;

-- CHAP 90

USE SQL_STORE;
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
START TRANSACTION;
SELECT * FROM CUSTOMERS WHERE STATE = 'VA';
-- SELECT POINTS FROM CUSTOMERS WHERE CUSTOMER_ID = 1;
COMMIT;

-- CHAP 91

USE SQL_STORE;
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
START TRANSACTION;
SELECT * FROM CUSTOMERS WHERE STATE = 'VA';
-- SELECT POINTS FROM CUSTOMERS WHERE CUSTOMER_ID = 1;
COMMIT;

-- CHAP 92

USE SQL_STORE;
START TRANSACTION;
UPDATE CUSTOMERS SET STATE = 'VA' WHERE CUSTOMER_ID = 1;
UPDATE ORDERS SET STATUS = 1 WHERE ORDER_ID = 1;
COMMIT; 